name: isbndb
description: Dart service for isbndb.com API. Returns book details from an ISBN, or a list of books from an author name, etc.
version: 0.3.0
repository: https://github.com/julienlebren/flutter_ISBNdb
issue_tracker: https://github.com/julienlebren/flutter_ISBNdb/issues

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  dio: ^5.3.2
  freezed_annotation: ^2.4.1
  intl: ^0.18.0
  universal_io: ^2.0.4

dev_dependencies:
  build_runner: ^2.1.8
  flutter_lints: ^1.0.0
  freezed: ^2.4.2
  json_serializable: ^6.1.5
  test: ^1.24.5
